spring:
  datasource:
#    mysql
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    oracle
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: HEHAO
#    password: root
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181